name: Create Release

on:
  push:
    tags:
      - 'v*' # This will match tags like v2024.3, v1.0.0, etc.

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Create Release
        uses: ./.github/actions
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}